### ISSUE TITLE
Bot leave voice channel, when i want to play music

### ISSUE THREAD

**Issue by docentYT** [Tomato6966/Music-Bot-with-Filters-#1]
When i type `!play [title]` bot join to voice channel and leave immediately.

Console log:
Error: input stream: Status code: 429
    at ClientRequest.<anonymous> (/home/container/node_modules/miniget/dist/index.js:150:31)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:475:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)

**Comment by Tomato6966** [comment]
you made too many youtube request

**Comment by docentYT** [comment]
> you made too many youtube request

 I want play only one song.
